version: "2"
services:
    web:
        build:
            context: .
            dockerfile: container-build/web/Dockerfile
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_HOST=${DB_HOST}
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
        depends_on:
            - db
    db:
        image: mysql
        # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
        # (this is just an example, not intended to be a production configuration)
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8081:80
        environment:
            - PMA_ARBITRARY=1
volumes:
    mysql_data: { driver: local }
networks:
    php-network:
        driver: bridge
